version: '3.9'
services:
  frontend:
    build: ./onchain-riddle-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}

  bot:
    build: ./onchain-riddle-bot
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
    restart: always
